name: Manual Build and Deploy

on:
  workflow_dispatch:  # Runs only when manually triggered

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21 (Amazon Corretto)
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Grant execute permissions to Gradle
        run: chmod +x ./gradlew

      - name: Create local.properties file
        run: |
          cat > local.properties << EOF
          BASE_URL=${{ secrets.BASE_URL }}
          FIREBASE_BASE_URL=${{ secrets.FIREBASE_BASE_URL }}
          FIREBASE_BEARER=${{ secrets.FIREBASE_BEARER }}
          GIT_TOKEN=${{ secrets.GIT_TOKEN }}
          GIT_BASE_URL=${{ secrets.GIT_BASE_URL }}
          SHA_SECRET_KEY=${{ secrets.SHA_SECRET_KEY }}
          gpr.user=${{ secrets.GPR_USER }}
          gpr.key=${{ secrets.GPR_KEY }}
          EOF
          echo "✅ local.properties created"

      - name: Build buildSrc (compile sitemap generator)
        run: ./gradlew :buildSrc:build

      - name: Generate sitemap.xml with dynamic blog data
        run: ./gradlew :composeApp:generateSitemap

      - name: Build Wasm JS distribution
        run: ./gradlew wasmJsBrowserDistribution

      - name: Copy sitemap.xml to distribution folder
        run: |
          cp composeApp/src/wasmJsMain/resources/sitemap.xml \
             composeApp/build/dist/wasmJs/productionExecutable/sitemap.xml
          echo "✅ Sitemap copied to distribution folder"

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Authenticate Firebase using Service Account
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > "$HOME/firebase-key.json"
          export GOOGLE_APPLICATION_CREDENTIALS="$HOME/firebase-key.json"

      - name: Deploy to Firebase
        run: firebase deploy --project bluelabs-41aef
